### ISSUE TITLE
HDA0008: Onboard Oauth2 account linking

### ISSUE THREAD

**Issue by zoomzoomTnT** [zoomzoomTnT/archer#10]
Requirements:
- As a team member, I want to made a new feature for the account linking with Oauth2, so that different Oauth2 provider can register a unique account with archer account service.

Acceptance Criteria:
- [ ] Gather requirements for Oauth2 account linking
- [ ] Users can login with any 2 oauth2 provider and still able to access the same account content
- [ ] 2 oauth2 providers are google, github, (facebook, wechat)
- [ ] account content nonnull fields: email, phone
- [ ] Update UML Diagram and save to WIKI **before commit**

Additional Information:

Story Points:
3 @zhang1995

**Comment by zhang1995** [comment]
added support for google

**Comment by zhang1995** [comment]
pushed to HDA-0009 branch
AuthenticationController.java
OAuth2Config.java
